fix compilation with xcode 4.2.1
xcode is based on llvm-gcc, which btw is deprecated. The compilation
of libev bails out with:

,----
| libev/ev.c:885:3: error: #error "memory fences not defined for your architecture, please report"
`----

We work around it by undefining __llvm__ which makes ev.c trust
gcc-llvm's advertised gcc version.

See http://lists.schmorp.de/pipermail/libev/2011q4/001618.html for a
discussion of the issues involved.